# Generated by Django 6.0.4 on 2026-05-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diagnosisrecord_patient_role_alter_patient_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrecord',
            name='severity',
            field=models.CharField(default='Low', max_length=50),
        ),
    ]
